/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangChaptersIndexRouteImport } from './routes/$lang.chapters.index'
import { Route as LangChaptersChapterIdRouteImport } from './routes/$lang.chapters.$chapterId'
import { Route as LangSongsIndexRouteImport } from './routes/$lang.songs.index'
import { Route as LangSongsSongIdRouteImport } from './routes/$lang.songs.$songId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangChaptersIndexRoute = LangChaptersIndexRouteImport.update({
  id: '/chapters/',
  path: '/chapters/',
  getParentRoute: () => LangRoute,
} as any)
const LangChaptersChapterIdRoute = LangChaptersChapterIdRouteImport.update({
  id: '/chapters/$chapterId',
  path: '/chapters/$chapterId',
  getParentRoute: () => LangRoute,
} as any)
const LangSongsIndexRoute = LangSongsIndexRouteImport.update({
  id: '/songs/',
  path: '/songs/',
  getParentRoute: () => LangRoute,
} as any)
const LangSongsSongIdRoute = LangSongsSongIdRouteImport.update({
  id: '/songs/$songId',
  path: '/songs/$songId',
  getParentRoute: () => LangRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/chapters/$chapterId': typeof LangChaptersChapterIdRoute
  '/$lang/songs/$songId': typeof LangSongsSongIdRoute
  '/$lang/chapters/': typeof LangChaptersIndexRoute
  '/$lang/songs/': typeof LangSongsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/chapters/$chapterId': typeof LangChaptersChapterIdRoute
  '/$lang/songs/$songId': typeof LangSongsSongIdRoute
  '/$lang/chapters': typeof LangChaptersIndexRoute
  '/$lang/songs': typeof LangSongsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/': typeof LangIndexRoute
  '/$lang/chapters/$chapterId': typeof LangChaptersChapterIdRoute
  '/$lang/songs/$songId': typeof LangSongsSongIdRoute
  '/$lang/chapters/': typeof LangChaptersIndexRoute
  '/$lang/songs/': typeof LangSongsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/'
    | '/$lang/chapters/$chapterId'
    | '/$lang/songs/$songId'
    | '/$lang/chapters/'
    | '/$lang/songs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/$lang/chapters/$chapterId'
    | '/$lang/songs/$songId'
    | '/$lang/chapters'
    | '/$lang/songs'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/'
    | '/$lang/chapters/$chapterId'
    | '/$lang/songs/$songId'
    | '/$lang/chapters/'
    | '/$lang/songs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/chapters/': {
      id: '/$lang/chapters/'
      path: '/chapters'
      fullPath: '/$lang/chapters/'
      preLoaderRoute: typeof LangChaptersIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/chapters/$chapterId': {
      id: '/$lang/chapters/$chapterId'
      path: '/chapters/$chapterId'
      fullPath: '/$lang/chapters/$chapterId'
      preLoaderRoute: typeof LangChaptersChapterIdRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/songs/': {
      id: '/$lang/songs/'
      path: '/songs'
      fullPath: '/$lang/songs/'
      preLoaderRoute: typeof LangSongsIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/songs/$songId': {
      id: '/$lang/songs/$songId'
      path: '/songs/$songId'
      fullPath: '/$lang/songs/$songId'
      preLoaderRoute: typeof LangSongsSongIdRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface LangRouteChildren {
  LangIndexRoute: typeof LangIndexRoute
  LangChaptersChapterIdRoute: typeof LangChaptersChapterIdRoute
  LangSongsSongIdRoute: typeof LangSongsSongIdRoute
  LangChaptersIndexRoute: typeof LangChaptersIndexRoute
  LangSongsIndexRoute: typeof LangSongsIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangIndexRoute: LangIndexRoute,
  LangChaptersChapterIdRoute: LangChaptersChapterIdRoute,
  LangSongsSongIdRoute: LangSongsSongIdRoute,
  LangChaptersIndexRoute: LangChaptersIndexRoute,
  LangSongsIndexRoute: LangSongsIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
